### ISSUE TITLE
No plugins available in the list

### ISSUE THREAD

**Issue by nimaforoughi** [LDO-CERT/orochi#632]
On kali, no plugins can be seen in the list.
All the containers are running properly with no error.

![image](https://user-images.githubusercontent.com/90676852/164383000-5ae51c86-f829-440e-bf95-4cc6486eb0d4.png)

![image](https://user-images.githubusercontent.com/90676852/164383184-9bc9b72b-a6ec-47ba-a92a-8cdcf201743a.png)

**Comment by garanews** [comment]
at first run you need to update plugins, go under admin:
![image](https://user-images.githubusercontent.com/16938405/165058163-31bf6206-a774-403a-ad07-922953eeff7b.png)
Then press update plugins
![image](https://user-images.githubusercontent.com/16938405/165058423-a5d05d3c-2f61-491d-b9dd-641a81bbec16.png)
you will read when done
![image](https://user-images.githubusercontent.com/16938405/165058520-c4ad19be-a5c4-4523-b1cc-92001ffd6fc2.png)
and also in the logs
![image](https://user-images.githubusercontent.com/16938405/165058598-fd652354-ae5f-4e6a-909d-107a6d96a37f.png)
Then go back with view site
![image](https://user-images.githubusercontent.com/16938405/165058700-04a9bb4c-1dbb-4744-a0f7-86ea083acac8.png)
select the image again and here you go
![image](https://user-images.githubusercontent.com/16938405/165058750-37a65a2b-b4d0-4ed5-8b85-6bc254c3df38.png)

**Comment by nimaforoughi** [comment]
Thank you so much, Now plugins are available but still no results.
I have tried many memory images stuxnet.vmem, dridex.vmem ... with different OS systems. All the 9 containers are running properly. 
None of the plugins work. all show "No data available in table"

**Comment by garanews** [comment]
Select the plugin you want to run, then press the "reload" button
![image](https://user-images.githubusercontent.com/16938405/165238705-165008e8-ffa1-4238-8be6-bf3b3f022750.png)
then press rerun plugin
![image](https://user-images.githubusercontent.com/16938405/165238781-0486cc4d-063a-4a28-8fa8-f5810ffecfe7.png)
when done you can just click again on the plugin
![image](https://user-images.githubusercontent.com/16938405/165239140-a6613e4d-3ec6-475a-b157-80bf8350409d.png)
or the results will happear automatically if enabled auto-refresh
![image](https://user-images.githubusercontent.com/16938405/165239243-8ea0eae5-3723-4476-9bb7-ac2d6e61cccf.png)

We called re run plugins because you can enable wich plugins you want to be run automatically when image is uploaded, doing from here
![image](https://user-images.githubusercontent.com/16938405/165239487-9804dcbb-f963-4b22-9e5c-92cf5e660643.png)
In this example any image I will upload, the windows pslist and windows pstree plugins will be executed automatically
![image](https://user-images.githubusercontent.com/16938405/165239704-fe55c12f-581d-4a15-b2b0-5f42edb3372c.png)

**Comment by nimaforoughi** [comment]
Yes fixed. Thanks.
