### ISSUE TITLE
custom plugins error of Ooops!!! 500

### ISSUE THREAD

**Issue by nimaforoughi** [LDO-CERT/orochi#636]
Adding custom plugins gives me error of Ooops!!! 500. I have tried many plugins including the examples like : autorun and pehash. Autorun.py and pehash.zip with all required files.

**Comment by garanews** [comment]
Just tried autoruns:
![image](https://user-images.githubusercontent.com/16938405/165451503-6b7fdcb9-df27-492a-ba18-1ba973ab2f26.png)
![image](https://user-images.githubusercontent.com/16938405/165451536-d82657d8-1b59-42cd-8894-781a4239130b.png)
![image](https://user-images.githubusercontent.com/16938405/165452286-31604cdb-72b2-4c74-995a-2593bc2f4f84.png)

The import works with any issue.
Steps I followed:
download autoruns.py
add it to zip file (so have autoruns.zip that contains autoruns.py)
go in the admin plugin and upload it (selecting windows) and save
return on the dump images and run the new plugin

Just for info, the autoruns should have framework version 2 so I had to modify this row
https://github.com/Telindus-CSIRT/volatility3-autoruns/blob/main/autorun.py#L148
```    _required_framework_version = (1, 0, 0) ```
in
```    _required_framework_version = (2, 0, 0) ```

otherwise system will report that plugin is using a framework not supported

**Comment by nimaforoughi** [comment]
It worked. Thanks a lot 🙏
You are doing fantastic . Orochi is amazing
